name: Lint Docs with Vale

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Setup DevEnv
      uses: devcontainers/ci@v0.3

    - name: Run Vale
      run: |
        vale --version
        vale docs/